// Mamba's depthwise causal conv over time, bit-identical to MLX 0.32.3's depthwise_conv_1d (bfloat16).
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;

namespace tfp {

// One output (channel, time, batch) over a grid of exactly that shape: fp32 sum of exact bf16 products, taps in order.
template <typename T>
inline void conv1d_depthwise(const device T* x, const device T* w, device T* y, const device int* P, uint3 at,
                             uint3 grid) {
  y += (int(at.z) * int(grid.y) + int(at.y)) * int(grid.x) + int(at.x);
  x += int(at.z) * P[0] + int(at.y) * P[1] + int(at.x) * P[2];
  w += int(at.x) * P[3];
  float acc = 0.0f;
  for (int k = 0; k < P[3]; k++) {
    acc += static_cast<float>(x[0]) * w[k];
    x += P[1];
  }
  y[0] = static_cast<T>(acc);
}

}  // namespace tfp
// ---- entry points: generated by tools/zig/check_prefill_ops.py --write ----
[[kernel]] void custom_kernel_tf_conv1d_depthwise_bf16_bfloat16_t_bfloat16_t_int32_t_bfloat16_t(
  const device bfloat16_t* X [[buffer(0)]],
  const device bfloat16_t* W [[buffer(1)]],
  const device int32_t* P [[buffer(2)]],
  device bfloat16_t* Y [[buffer(3)]],
  uint3 thread_position_in_grid [[thread_position_in_grid]],
  uint3 threads_per_grid [[threads_per_grid]]) {
  tfp::conv1d_depthwise<bfloat16_t>(X, W, Y, P, thread_position_in_grid, threads_per_grid);

}
