// The SSD's batched fp32 matrix-vector step (state @ C), bit-identical to MLX 0.32.3's gemv_float32_bm4_bn1_sm1_sn32.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;

namespace tfp {

// Offset of batch element i in a row-major batch shape with the given strides (innermost dimension last).
inline long batch_at(int i, const device int* shape, const device int* strides, int ndim) {
  long at = 0;
  for (int d = ndim - 1; d >= 0 && i > 0; d--) {
    at += long(i % shape[d]) * strides[d];
    i /= shape[d];
  }
  return at;
}

// y = A x per batch: TM rows a simdgroup, TN inputs a lane a step, lanes summed down from 16; P: GEMV_PARAMS fields.
template <typename T, int BM, int TM, int TN>
inline void gemv_rows(const device T* A, const device T* x, device T* y, const device int* P, uint3 tg, uint sg,
                      uint lane) {
  constexpr int SPAN = 32 * TN;
  const int K = P[0], M = P[1], lda = P[2], ndim = P[3];
  x += batch_at(int(tg.z), P + 4, P + 8, ndim);
  A += batch_at(int(tg.z), P + 4, P + 12, ndim);
  y += long(tg.z) * M;
  int row = int(tg.x) * (BM * TM) + int(sg) * TM;
  if (row >= M) {
    return;
  }
  row = row + TM <= M ? row : M - TM;
  A += long(row) * lda;
  float acc[TM];
  for (short m = 0; m < TM; m++) {
    acc[m] = 0.0f;
  }
  int k = int(lane) * TN;
  const int whole = K / SPAN;
  for (int it = 0; it < whole; it++, k += SPAN) {
    float xv[TN];
    for (short j = 0; j < TN; j++) {
      xv[j] = float(x[k + j]);
    }
    for (short m = 0; m < TM; m++) {
      T a[TN];
      for (short j = 0; j < TN; j++) {
        a[j] = A[m * lda + k + j];
      }
      for (short j = 0; j < TN; j++) {
        acc[m] += a[j] * xv[j];
      }
    }
  }
  if (K - whole * SPAN > 0) {
    float xv[TN];
    for (short j = 0; j < TN; j++) {
      xv[j] = k + j < K ? float(x[k + j]) : 0.0f;
    }
    for (short m = 0; m < TM; m++) {
      T a[TN];
      for (short j = 0; j < TN; j++) {
        a[j] = k + j < K ? A[m * lda + k + j] : T(0);
      }
      for (short j = 0; j < TN; j++) {
        acc[m] += a[j] * xv[j];
      }
    }
  }
  for (short m = 0; m < TM; m++) {
    for (ushort d = 16; d >= 1; d >>= 1) {
      acc[m] += simd_shuffle_down(acc[m], d);
    }
  }
  if (lane == 0) {
    for (short m = 0; m < TM; m++) {
      y[row + m] = T(acc[m]);
    }
  }
}

}  // namespace tfp
// ---- entry points: generated by tools/zig/check_prefill_ops.py --write ----
[[max_total_threads_per_threadgroup(128)]]
[[kernel]] void custom_kernel_tf_gemv_rows_f32_4_4_4_float_float_int32_t_float(
  const device float* A [[buffer(0)]],
  const device float* X [[buffer(1)]],
  const device int32_t* P [[buffer(2)]],
  device float* Y [[buffer(3)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {
  tfp::gemv_rows<float, 4, 4, 4>(A, X, Y, P, threadgroup_position_in_grid, simdgroup_index_in_threadgroup, thread_index_in_simdgroup);

}
