// Inclusive sums along a strided axis, bit-identical to MLX 0.32.3's strided_scan_inclusive_sum (float32).
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;

namespace tfp {

// x (from P[3]) as [outer][axis][stride], 32 columns a threadgroup: lanes scan rows of 32 with simd prefix sums.
template <typename T>
inline void scan_sum_strided(const device T* x, device T* y, const device int* P, threadgroup T* tile, uint3 tg,
                             uint3 groups, uint t, uint sg, uint lane) {
  constexpr int N = 4, PAD = 32 + 16 / sizeof(T);
  const int axis = P[0], stride = P[1], blocks = P[2];
  x += P[3];
  const ulong slice = ulong(tg.y) + ulong(groups.y) * tg.z;
  const ulong base = slice / ulong(blocks) * ulong(axis) * ulong(stride);
  const int col = int(slice % ulong(blocks)) * 32;
  const int row_in = int(t * N) / 32, col_in = int(t * N) % 32;
  const int cols_left = stride - col;
  x += base + col + col_in;
  y += base + col + col_in;
  threadgroup T* mine = tile + row_in * PAD + col_in;
  threadgroup T* lanes = tile + lane * PAD + sg * N;
  T carry[N];
  for (short i = 0; i < N; i++) {
    carry[i] = T(0);
  }
  for (int r0 = 0; r0 < axis; r0 += 32) {
    const int r = r0 + row_in;
    const bool whole = r < axis && col_in + N < cols_left;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (short i = 0; i < N; i++) {
      mine[i] = (whole || (r < axis && col_in + i < cols_left)) ? x[ulong(r) * ulong(stride) + i] : T(0);
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    T v[N];
    for (short i = 0; i < N; i++) {
      v[i] = lanes[i];
    }
    simdgroup_barrier(mem_flags::mem_threadgroup);
    for (short i = 0; i < N; i++) {
      v[i] = simd_prefix_inclusive_sum(v[i]);
      v[i] = v[i] + carry[i];
      carry[i] = simd_shuffle(v[i], ushort(31));
    }
    for (short i = 0; i < N; i++) {
      lanes[i] = v[i];
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (short i = 0; i < N; i++) {
      if (whole || (r < axis && col_in + i < cols_left)) {
        y[ulong(r) * ulong(stride) + i] = mine[i];
      }
    }
  }
}

}  // namespace tfp
// ---- entry points: generated by tools/zig/check_prefill_ops.py --write ----
[[kernel]] void custom_kernel_tf_scan_sum_strided_f32_float_int32_t_float(
  const device float* X [[buffer(0)]],
  const device int32_t* P [[buffer(1)]],
  device float* Y [[buffer(2)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint thread_index_in_threadgroup [[thread_index_in_threadgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]],
  uint3 threadgroups_per_grid [[threadgroups_per_grid]]) {
  threadgroup float tile[32 * (32 + 16 / sizeof(float))];
  tfp::scan_sum_strided<float>(X, Y, P, tile, threadgroup_position_in_grid, threadgroups_per_grid,
                             thread_index_in_threadgroup, simdgroup_index_in_threadgroup,
                             thread_index_in_simdgroup);

}
