// Stable argsorts of expert ids and their inverse, bit-identical to MLX 0.32.3's carg_block_sort and mbsort on uint32.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;

namespace tfp {

// MLX's sorts are stable merge sorts, so a stable counting sort gives their order. Blocks of 256 keys; P: n experts.
inline void sort_count(const device uint32_t* keys, device int32_t* counts, const device int* P,
                       threadgroup atomic_uint* hist, uint block, uint t) {
  const int n = P[0], experts = P[1];
  for (int e = int(t); e < experts; e += 256) {
    atomic_store_explicit(&hist[e], 0u, memory_order_relaxed);
  }
  threadgroup_barrier(mem_flags::mem_threadgroup);
  const int i = int(block) * 256 + int(t);
  if (i < n) {
    atomic_fetch_add_explicit(&hist[keys[i]], 1u, memory_order_relaxed);
  }
  threadgroup_barrier(mem_flags::mem_threadgroup);
  for (int e = int(t); e < experts; e += 256) {
    counts[long(block) * experts + e] = int(atomic_load_explicit(&hist[e], memory_order_relaxed));
  }
}

// Each block's first slot per expert, and offsets[e] = the first sorted slot of expert e (MLX's gather_mm_offsets).
inline void sort_starts(const device int32_t* counts, device int32_t* starts, device int32_t* offsets,
                        const device int* P, threadgroup int* totals, uint e) {
  const int n = P[0], experts = P[1], blocks = (n + 255) / 256;
  if (int(e) < experts) {
    int total = 0;
    for (int b = 0; b < blocks; b++) {
      total += counts[long(b) * experts + e];
    }
    totals[e] = total;
  }
  threadgroup_barrier(mem_flags::mem_threadgroup);
  if (int(e) < experts) {
    int base = 0;
    for (int j = 0; j < int(e); j++) {
      base += totals[j];
    }
    offsets[e] = base;
    for (int b = 0; b < blocks; b++) {
      starts[long(b) * experts + e] = base;
      base += counts[long(b) * experts + e];
    }
  }
}

// order[slot] = i and sorted[slot] = keys[i], slot = the block's start for the key plus earlier equal keys in the block.
inline void sort_place(const device uint32_t* keys, const device int32_t* starts, device uint32_t* order,
                       device uint32_t* sorted, const device int* P, threadgroup uint* local, uint block, uint t) {
  const int n = P[0], experts = P[1], i = int(block) * 256 + int(t);
  local[t] = i < n ? keys[i] : 0xffffffffu;
  threadgroup_barrier(mem_flags::mem_threadgroup);
  if (i >= n) {
    return;
  }
  const uint key = local[t];
  int rank = 0;
  for (uint j = 0; j < t; j++) {
    rank += local[j] == key ? 1 : 0;
  }
  const int slot = starts[long(block) * experts + key] + rank;
  order[slot] = uint(i);
  sorted[slot] = key;
}

// inverse[order[i]] = i: the argsort of a permutation (MLX sorts it again to unsort the experts' rows).
inline void sort_inverse(const device uint32_t* order, device uint32_t* inverse, const device int* P, uint i) {
  if (int(i) < P[0]) {
    inverse[order[i]] = i;
  }
}

}  // namespace tfp
// ---- entry points: generated by tools/zig/check_prefill_ops.py --write ----
[[kernel]] void custom_kernel_tf_sort_count_uint32_t_int32_t_int32_t(
  const device uint32_t* KEYS [[buffer(0)]],
  const device int32_t* P [[buffer(1)]],
  device int32_t* COUNTS [[buffer(2)]],
  uint thread_index_in_threadgroup [[thread_index_in_threadgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {
  threadgroup atomic_uint hist[1024];
  tfp::sort_count(KEYS, COUNTS, P, hist, threadgroup_position_in_grid.x, thread_index_in_threadgroup);

}
[[kernel]] void custom_kernel_tf_sort_inverse_uint32_t_int32_t_uint32_t(
  const device uint32_t* ORDER [[buffer(0)]],
  const device int32_t* P [[buffer(1)]],
  device uint32_t* INV [[buffer(2)]],
  uint3 thread_position_in_grid [[thread_position_in_grid]]) {
  tfp::sort_inverse(ORDER, INV, P, thread_position_in_grid.x);

}
[[kernel]] void custom_kernel_tf_sort_place_uint32_t_int32_t_int32_t_uint32_t_uint32_t(
  const device uint32_t* KEYS [[buffer(0)]],
  const device int32_t* STARTS [[buffer(1)]],
  const device int32_t* P [[buffer(2)]],
  device uint32_t* ORDER [[buffer(3)]],
  device uint32_t* SORTED [[buffer(4)]],
  uint thread_index_in_threadgroup [[thread_index_in_threadgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {
  threadgroup uint local[256];
  tfp::sort_place(KEYS, STARTS, ORDER, SORTED, P, local, threadgroup_position_in_grid.x, thread_index_in_threadgroup);

}
[[kernel]] void custom_kernel_tf_sort_starts_int32_t_int32_t_int32_t_int32_t(
  const device int32_t* COUNTS [[buffer(0)]],
  const device int32_t* P [[buffer(1)]],
  device int32_t* STARTS [[buffer(2)]],
  device int32_t* OFFSETS [[buffer(3)]],
  uint thread_index_in_threadgroup [[thread_index_in_threadgroup]]) {
  threadgroup int totals[1024];
  tfp::sort_starts(COUNTS, STARTS, OFFSETS, P, totals, thread_index_in_threadgroup);

}
