// Generated by tools/zig/gen_nemotron_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
template <int D, int T>
[[kernel]] void custom_kernel_nemotron_add_norm_xs_ff2bfad9575aba69__2688_896_bfloat16_t_bfloat16_t_bfloat16_t_floatc_int32_t_bfloat16_t_bfloat16_t_float(
  const device bfloat16_t* H [[buffer(0)]],
  const device bfloat16_t* X [[buffer(1)]],
  const device bfloat16_t* W [[buffer(2)]],
  const constant float* eps [[buffer(3)]],
  const device int32_t* dims [[buffer(4)]],
  device bfloat16_t* HN [[buffer(5)]],
  device bfloat16_t* OUT [[buffer(6)]],
  device float* XS [[buffer(7)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 thread_position_in_threadgroup [[thread_position_in_threadgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {

  const uint t = thread_position_in_threadgroup.x;
  const uint r = threadgroup_position_in_grid.x;
  threadgroup bfloat xb[D];
  if (int(r) >= dims[0]) {
    for (int g = int(t); g < D / 64; g += T) XS[g * dims[1] + int(r)] = 0.0f;
    return;
  }
  constexpr int PER = D / T;
  threadgroup float partial[T / 32];
  float hv[PER];
  float ss = 0.0f;
  for (int i = 0; i < PER; i++) {
    const int c = int(t) + i * T;
    const int at = int(r) * D + c;
    float delta;
    delta = float(X[at]);
    const bfloat hn = bfloat(float(H[at]) + delta);
    HN[at] = hn;
    hv[i] = float(hn);
    ss = fma(hv[i], hv[i], ss);
  }
  ss = simd_sum(ss);
  if (thread_index_in_simdgroup == 0) partial[simdgroup_index_in_threadgroup] = ss;
  threadgroup_barrier(mem_flags::mem_threadgroup);
  float total = 0.0f;
  for (int s = 0; s < T / 32; s++) total += partial[s];
  const float scale = metal::rsqrt(total / float(D) + eps[0]);
  for (int i = 0; i < PER; i++) {
    const int c = int(t) + i * T;
    const bfloat x = bfloat(float(W[c]) * (hv[i] * scale));
    OUT[int(r) * D + c] = x;
    xb[c] = x;
  }
  threadgroup_barrier(mem_flags::mem_threadgroup);
  for (int g = int(t); g < D / 64; g += T) {
    float acc = 0.0f;
    for (int i = 0; i < 64; i++) acc += float(xb[g * 64 + i]);
    XS[g * dims[1] + int(r)] = acc;
  }

}

template [[host_name("custom_kernel_nemotron_add_norm_xs_ff2bfad9575aba69__2688_896_bfloat16_t_bfloat16_t_bfloat16_t_floatc_int32_t_bfloat16_t_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_nemotron_add_norm_xs_ff2bfad9575aba69__2688_896_bfloat16_t_bfloat16_t_bfloat16_t_floatc_int32_t_bfloat16_t_bfloat16_t_float<2688, 896>) custom_kernel_nemotron_add_norm_xs_ff2bfad9575aba69__2688_896_bfloat16_t_bfloat16_t_bfloat16_t_floatc_int32_t_bfloat16_t_bfloat16_t_float<2688, 896>;
