// Generated by tools/zig/gen_nemotron_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
#include <MetalPerformancePrimitives/MetalPerformancePrimitives.h>
using namespace mpp::tensor_ops;
template <int G, int D>
[[kernel]] void custom_kernel_lane_attention_merge_da4fb5aad03402b1__16_128_float_float_float_int32_tc_bfloat16_t(
  const device float* PO [[buffer(0)]],
  const device float* PM [[buffer(1)]],
  const device float* PL [[buffer(2)]],
  const constant int32_t* dims [[buffer(3)]],
  device bfloat16_t* OUT [[buffer(4)]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {

  const uint lane = thread_index_in_simdgroup;
  const uint hk = threadgroup_position_in_grid.x;
  const uint r = threadgroup_position_in_grid.y;
  const int NCH = dims[1], NQ = dims[2], SGA = dims[4];
  const int RP = 16 * SGA;
  constexpr int DP = D / 32;
  float m = -INFINITY, l = 0.0f, o[DP];
  for (int i = 0; i < DP; i++) o[i] = 0.0f;
  for (int c = 0; c < NCH; c++) {
    const int64_t row = ((int64_t)hk * NCH + c) * RP + r;
    const float mc = PM[row];
    if (mc == -INFINITY) continue;
    const float lc = PL[row];
    const float nm = max(m, mc);
    const float f1 = fast::exp(m - nm), f2 = fast::exp(mc - nm);
    l = l * f1 + lc * f2;
    for (int i = 0; i < DP; i++) o[i] = o[i] * f1 + PO[row * D + lane * DP + i] * f2;
    m = nm;
  }
  const int t = r / G, g = r % G, h = hk * G + g;
  for (int i = 0; i < DP; i++) OUT[((int64_t)h * NQ + t) * D + lane * DP + i] = static_cast<bfloat>(o[i] / l);

}

template [[host_name("custom_kernel_lane_attention_merge_da4fb5aad03402b1__16_128_float_float_float_int32_tc_bfloat16_t")]] [[kernel]] decltype(custom_kernel_lane_attention_merge_da4fb5aad03402b1__16_128_float_float_float_int32_tc_bfloat16_t<16, 128>) custom_kernel_lane_attention_merge_da4fb5aad03402b1__16_128_float_float_float_int32_tc_bfloat16_t<16, 128>;
