// Generated by tools/zig/gen_nemotron_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;

#include <MetalPerformancePrimitives/MetalPerformancePrimitives.h>
using namespace mpp::tensor_ops;
[[kernel]] void custom_kernel_nemotron_group_norm_xs_d5ea27bb1dcaa1a5_bfloat16_t_bfloat16_t_floatc_int32_t_bfloat16_t_float(
  const device bfloat16_t* X [[buffer(0)]],
  const device bfloat16_t* W [[buffer(1)]],
  const constant float* eps [[buffer(2)]],
  const device int32_t* dims [[buffer(3)]],
  device bfloat16_t* OUT [[buffer(4)]],
  device float* XS [[buffer(5)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 thread_position_in_threadgroup [[thread_position_in_threadgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {
  constexpr int XD = 4096;
  constexpr int GS = 512;
  constexpr int MP = 16;

  const uint t = thread_position_in_threadgroup.x;
  const uint grp = threadgroup_position_in_grid.x;
  const uint r = threadgroup_position_in_grid.y;
  constexpr int SUB = GS / 64;
  if (int(r) >= dims[0]) {
    for (int s = int(thread_position_in_threadgroup.x); s < SUB; s += GS / 4) XS[(int(grp) * SUB + s) * MP + int(r)] = 0.0f;
    return;
  }
  threadgroup bfloat outv[GS];
  constexpr int T = GS / 4;
  threadgroup float partial[T / 32];
  const int base = int(r) * XD + int(grp) * GS + int(t) * 4;
  float v[4];
  float ss = 0.0f;
  for (int i = 0; i < 4; i++) { v[i] = float(X[base + i]); ss = fma(v[i], v[i], ss); }
  ss = simd_sum(ss);
  if (thread_index_in_simdgroup == 0) partial[simdgroup_index_in_threadgroup] = ss;
  threadgroup_barrier(mem_flags::mem_threadgroup);
  float total = 0.0f;
  for (int s = 0; s < T / 32; s++) total += partial[s];
  const float scale = metal::rsqrt(total / float(GS) + eps[0]);
  for (int i = 0; i < 4; i++) {
    const int c = int(grp) * GS + int(t) * 4 + i;
    const bfloat o = bfloat(float(W[c]) * float(bfloat(v[i] * scale)));
    OUT[base + i] = o;
    outv[int(t) * 4 + i] = o;
  }
  threadgroup_barrier(mem_flags::mem_threadgroup);
  if (int(t) < SUB) {
    float acc = 0.0f;
    for (int i = 0; i < 64; i++) acc += float(outv[int(t) * 64 + i]);
    XS[(int(grp) * SUB + int(t)) * MP + int(r)] = acc;
  }

}
