// Generated by tools/zig/gen_nemotron_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
template <int H, int DH, int NG, int DS, int XD, int PROJ, int DTOFF, int SSZ>
[[kernel]] void custom_kernel_nemotron_mamba_scan_52242b2ed609b53e__64_64_8_128_4096_10304_10240_524288_bfloat16_t_bfloat16_t_float_float_float_float_floatc_int32_tc_int32_t_int32_t_int32_t_bfloat16_t_float(
  const device bfloat16_t* P [[buffer(0)]],
  const device bfloat16_t* XBC [[buffer(1)]],
  const device float* S_IN [[buffer(2)]],
  const device float* A_LOG [[buffer(3)]],
  const device float* DSKIP [[buffer(4)]],
  const device float* DT_BIAS [[buffer(5)]],
  const constant float* limits [[buffer(6)]],
  const constant int32_t* dims [[buffer(7)]],
  const device int32_t* SEG [[buffer(8)]],
  const device int32_t* SLOT [[buffer(9)]],
  const device int32_t* STORE [[buffer(10)]],
  device bfloat16_t* Y [[buffer(11)]],
  device float* S_OUT [[buffer(12)]],
  uint3 thread_position_in_grid [[thread_position_in_grid]],
  uint3 thread_position_in_threadgroup [[thread_position_in_threadgroup]]) {

  const uint lane = thread_position_in_threadgroup.x;
  const uint d = thread_position_in_grid.y;
  const uint h = thread_position_in_grid.z;
  const uint g = h / (H / NG);
  const int R = dims[0];
  constexpr int NS = DS / 32;
  constexpr int CD = XD + 2 * NG * DS;
  const int cx = int(h) * DH + int(d);
  const int cb = XD + int(g) * DS + int(lane) * NS;
  const int cc = XD + NG * DS + int(g) * DS + int(lane) * NS;
  const int sbase = cx * DS + int(lane) * NS;
  const float A = -metal::exp(float(A_LOG[h]));
  const float dskip = float(bfloat(float(DSKIP[h])));
  const float dtb = float(DT_BIAS[h]);
  float st[NS];
  int cur = -1;
  for (int rr = 0; rr < R; rr++) {
    const int s = SEG[rr];
    if (s != cur) {
      cur = s;
      for (int i = 0; i < NS; i++) st[i] = float(S_IN[size_t(SLOT[s]) * SSZ + sbase + i]);
    }
    const float xv = float(XBC[rr * CD + cx]);
    float dt = float(P[rr * PROJ + DTOFF + int(h)]) + dtb;
    dt = metal::max(dt, 0.0f) + metal::log(1.0f + metal::exp(-metal::abs(dt)));
    dt = metal::clamp(dt, limits[0], limits[1]);
    const float dA = metal::exp(A * dt);
    const float xdt = xv * dt;
    float acc = 0.0f;
    for (int i = 0; i < NS; i++) {
      const float sv = dA * st[i] + xdt * float(XBC[rr * CD + cb + i]);
      st[i] = sv;
      acc += sv * float(XBC[rr * CD + cc + i]);
    }
    acc = simd_sum(acc);
    if (lane == 0) {
      const float y = float(bfloat(acc + xv * dskip));
      const float z = float(P[rr * PROJ + cx]);
      const float sz = float(bfloat(z / (1.0f + metal::exp(-z))));
      Y[rr * XD + cx] = bfloat(sz * y);
    }
    const int so = STORE[rr];
    if (so >= 0)
      for (int i = 0; i < NS; i++) S_OUT[size_t(so) * SSZ + sbase + i] = st[i];
  }

}

template [[host_name("custom_kernel_nemotron_mamba_scan_52242b2ed609b53e__64_64_8_128_4096_10304_10240_524288_bfloat16_t_bfloat16_t_float_float_float_float_floatc_int32_tc_int32_t_int32_t_int32_t_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_nemotron_mamba_scan_52242b2ed609b53e__64_64_8_128_4096_10304_10240_524288_bfloat16_t_bfloat16_t_float_float_float_float_floatc_int32_tc_int32_t_int32_t_int32_t_bfloat16_t_float<64, 64, 8, 128, 4096, 10304, 10240, 524288>) custom_kernel_nemotron_mamba_scan_52242b2ed609b53e__64_64_8_128_4096_10304_10240_524288_bfloat16_t_bfloat16_t_float_float_float_float_floatc_int32_tc_int32_t_int32_t_int32_t_bfloat16_t_float<64, 64, 8, 128, 4096, 10304, 10240, 524288>;
