// Generated by tools/zig/gen_nemotron_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
template <int XD, int NG, int DS, int KC, int PROJ, int XOFF>
[[kernel]] void custom_kernel_nemotron_mamba_conv_83552c1c128bdbca__4096_8_128_4_10304_4096_bfloat16_t_bfloat16_t_float_float_int32_t_int32_t_int32_t_int32_t_bfloat16_t_bfloat16_t(
  const device bfloat16_t* P [[buffer(0)]],
  const device bfloat16_t* CS_IN [[buffer(1)]],
  const device float* CW [[buffer(2)]],
  const device float* CB [[buffer(3)]],
  const device int32_t* SEG [[buffer(4)]],
  const device int32_t* START [[buffer(5)]],
  const device int32_t* SLOT [[buffer(6)]],
  const device int32_t* STORE [[buffer(7)]],
  device bfloat16_t* XBC [[buffer(8)]],
  device bfloat16_t* CS_OUT [[buffer(9)]],
  uint3 thread_position_in_grid [[thread_position_in_grid]]) {

  constexpr int CD = XD + 2 * NG * DS;
  const int ch = int(thread_position_in_grid.x);
  const int rr = int(thread_position_in_grid.y);
  const int s = SEG[rr];
  const int b = START[s];
  const int loc = rr - b;
  const int slot = SLOT[s];
  #define TAP(lp) ((lp) < 0 ? CS_IN[(slot * (KC - 1) + (lp) + KC - 1) * CD + ch] : P[(b + (lp)) * PROJ + XOFF + ch])
  float a = float(CB[ch]);
  for (int k = 0; k < KC; k++) a = fma(CW[k * CD + ch], float(TAP(loc - (KC - 1) + k)), a);
  const float cv = float(bfloat(a));
  XBC[rr * CD + ch] = bfloat(cv / (1.0f + metal::exp(-cv)));
  const int so = STORE[rr];
  if (so >= 0)
    for (int k = 0; k < KC - 1; k++) CS_OUT[(so * (KC - 1) + k) * CD + ch] = TAP(loc - (KC - 2) + k);
  #undef TAP

}

template [[host_name("custom_kernel_nemotron_mamba_conv_83552c1c128bdbca__4096_8_128_4_10304_4096_bfloat16_t_bfloat16_t_float_float_int32_t_int32_t_int32_t_int32_t_bfloat16_t_bfloat16_t")]] [[kernel]] decltype(custom_kernel_nemotron_mamba_conv_83552c1c128bdbca__4096_8_128_4_10304_4096_bfloat16_t_bfloat16_t_float_float_int32_t_int32_t_int32_t_int32_t_bfloat16_t_bfloat16_t<4096, 8, 128, 4, 10304, 4096>) custom_kernel_nemotron_mamba_conv_83552c1c128bdbca__4096_8_128_4_10304_4096_bfloat16_t_bfloat16_t_float_float_int32_t_int32_t_int32_t_int32_t_bfloat16_t_bfloat16_t<4096, 8, 128, 4, 10304, 4096>;
