// Generated by tools/zig/gen_nemotron_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
template <int NE, int K>
[[kernel]] void custom_kernel_nemotron_route_8776d7e9b3d3f6f3__128_6_bfloat16_t_float_floatc_uint32_t_float(
  const device bfloat16_t* G [[buffer(0)]],
  const device float* bias [[buffer(1)]],
  const constant float* scaling [[buffer(2)]],
  device uint32_t* IDX [[buffer(3)]],
  device float* WT [[buffer(4)]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {

  const uint lane = thread_index_in_simdgroup;
  const uint r = threadgroup_position_in_grid.x;
  float sel[NE / 32], prob[NE / 32];
  for (int j = 0; j < NE / 32; j++) {
    const int e = int(lane) + 32 * j;
    const float g = float(G[int(r) * NE + e]);
    prob[j] = 1.0f / (1.0f + metal::exp(-g));
    sel[j] = prob[j] + bias[e];
  }
  float total = 0.0f;
  float picked[K];
  for (int k = 0; k < K; k++) {
    float best = -INFINITY;
    int best_e = 1 << 20;
    for (int j = 0; j < NE / 32; j++) {
      const int e = int(lane) + 32 * j;
      if (sel[j] > best) { best = sel[j]; best_e = e; }
    }
    const float top = simd_max(best);
    const int winner = simd_min(best == top ? best_e : (1 << 20));
    float p = 0.0f;
    for (int j = 0; j < NE / 32; j++) {
      if (int(lane) + 32 * j == winner) { p = prob[j]; sel[j] = -INFINITY; }
    }
    p = simd_sum(p);
    picked[k] = p;
    total += p;
    if (lane == 0) IDX[int(r) * K + k] = uint(winner);
  }
  if (lane == 0) {
    const float denominator = total + 1e-20f;
    for (int k = 0; k < K; k++) WT[int(r) * K + k] = picked[k] / denominator * scaling[0];
  }

}

template [[host_name("custom_kernel_nemotron_route_8776d7e9b3d3f6f3__128_6_bfloat16_t_float_floatc_uint32_t_float")]] [[kernel]] decltype(custom_kernel_nemotron_route_8776d7e9b3d3f6f3__128_6_bfloat16_t_float_floatc_uint32_t_float<128, 6>) custom_kernel_nemotron_route_8776d7e9b3d3f6f3__128_6_bfloat16_t_float_floatc_uint32_t_float<128, 6>;
