// Generated by tools/zig/gen_nemotron_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
template <int D, int NE, int SG, int MAXR>
[[kernel]] void custom_kernel_nemotron_router_84d0c5e2f26dd05a__2688_128_8_16_bfloat16_t_bfloat16_t_int32_tc_bfloat16_t(
  const device bfloat16_t* X [[buffer(0)]],
  const device bfloat16_t* GW [[buffer(1)]],
  const constant int32_t* rows [[buffer(2)]],
  device bfloat16_t* OUT [[buffer(3)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {

  const uint lane = thread_index_in_simdgroup;
  const uint g = simdgroup_index_in_threadgroup;
  const int e = int(threadgroup_position_in_grid.y);
  const int rb = int(threadgroup_position_in_grid.z) * MAXR;
  const int R = min(rows[0] - rb, MAXR);
  constexpr int PART = D / SG;
  threadgroup float part[MAXR][SG];
  float acc[MAXR];
  for (int r = 0; r < MAXR; r++) acc[r] = 0.0f;
  const int begin = int(g) * PART;
  for (int c = begin + 4 * int(lane); c < begin + PART; c += 128) {
    const float w0 = float(GW[size_t(e) * D + c]), w1 = float(GW[size_t(e) * D + c + 1]);
    const float w2 = float(GW[size_t(e) * D + c + 2]), w3 = float(GW[size_t(e) * D + c + 3]);
    for (int r = 0; r < MAXR; r++) {
      if (r >= R) break;
      const device bfloat* xr = X + (rb + r) * D + c;
      acc[r] = fma(float(xr[3]), w3, fma(float(xr[2]), w2, fma(float(xr[1]), w1, fma(float(xr[0]), w0, acc[r]))));
    }
  }
  for (int r = 0; r < MAXR; r++) {
    if (r >= R) break;
    const float total = simd_sum(acc[r]);
    if (lane == 0) part[r][g] = total;
  }
  threadgroup_barrier(mem_flags::mem_threadgroup);
  if (g == 0 && int(lane) < R) {
    float total = 0.0f;
    for (int k = 0; k < SG; k++) total += part[lane][k];
    OUT[(rb + int(lane)) * NE + e] = bfloat(total);
  }

}

template [[host_name("custom_kernel_nemotron_router_84d0c5e2f26dd05a__2688_128_8_16_bfloat16_t_bfloat16_t_int32_tc_bfloat16_t")]] [[kernel]] decltype(custom_kernel_nemotron_router_84d0c5e2f26dd05a__2688_128_8_16_bfloat16_t_bfloat16_t_int32_tc_bfloat16_t<2688, 128, 8, 16>) custom_kernel_nemotron_router_84d0c5e2f26dd05a__2688_128_8_16_bfloat16_t_bfloat16_t_int32_tc_bfloat16_t<2688, 128, 8, 16>;
