// Generated by tools/zig/gen_nemotron_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;

inline float tf_load16(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
inline float tf_qdot16(const device uint8_t* w, const thread float* xt, float scale, float bias, float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += (xt[4 * i] * (ws[i] & 0x000f) + xt[4 * i + 1] * (ws[i] & 0x00f0) +
              xt[4 * i + 2] * (ws[i] & 0x0f00) + xt[4 * i + 3] * (ws[i] & 0xf000));
  return scale * accum + sum * bias;
}
template <int K, int GS, int RPS>
inline void tf_rowdot(const device uint8_t* w, const device bfloat* sc, const device bfloat* bi,
                      const device bfloat* x, uint lane, thread float* acc) {
  constexpr int KB = K / 2;
  constexpr int KG = K / GS;
  constexpr int FULL = K / 512 * 512;
  w += lane * 8;
  sc += lane / (GS / 16);
  bi += lane / (GS / 16);
  x += lane * 16;
  for (int j = 0; j < RPS; j++) acc[j] = 0.0f;
  for (int k0 = 0; k0 < FULL; k0 += 512) {
    float xt[16];
    const float sum = tf_load16(x, xt);
    for (int j = 0; j < RPS; j++) acc[j] += tf_qdot16(w + j * KB, xt, float(sc[j * KG]), float(bi[j * KG]), sum);
    w += 256; sc += 512 / GS; bi += 512 / GS; x += 512;
  }
  if (FULL < K && int(lane) < (K - FULL) / 16) {
    float xt[16];
    const float sum = tf_load16(x, xt);
    for (int j = 0; j < RPS; j++) acc[j] += tf_qdot16(w + j * KB, xt, float(sc[j * KG]), float(bi[j * KG]), sum);
  }
  for (int j = 0; j < RPS; j++) acc[j] = simd_sum(acc[j]);
}

[[max_total_threads_per_threadgroup(512)]]
[[kernel]] void custom_kernel_nemotron_rows_route_group_128_6_4fa7b8da8d929d0d_bfloat16_t_float_floatc_int32_tc_uint32_t_float_uint32_t_int32_t_int32_t_int32_t_int32_t(
  const device bfloat16_t* G [[buffer(0)]],
  const device float* bias [[buffer(1)]],
  const constant float* scaling [[buffer(2)]],
  const constant int32_t* rows [[buffer(3)]],
  device uint32_t* IDX [[buffer(4)]],
  device float* WT [[buffer(5)]],
  device uint32_t* UIDS [[buffer(6)]],
  device int32_t* START [[buffer(7)]],
  device int32_t* COUNT [[buffer(8)]],
  device int32_t* MEMBERS [[buffer(9)]],
  device int32_t* UCOUNT [[buffer(10)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 thread_position_in_threadgroup [[thread_position_in_threadgroup]]) {
  constexpr int NE = 128;
  constexpr int K = 6;
  constexpr int T = 512;
  constexpr int MAXP = 1024;

  const uint t = thread_position_in_threadgroup.x;
  const uint lane = thread_index_in_simdgroup;
  const uint sg = simdgroup_index_in_threadgroup;
  const int R = rows[0];
  const int P = R * K;
  threadgroup uint ids[MAXP];
  threadgroup int sg_pairs[T / 32], sg_used[T / 32];
  for (int r = int(sg); r < R; r += T / 32) {
    float sel[NE / 32], prob[NE / 32];
    for (int j = 0; j < NE / 32; j++) {
      const int e = int(lane) + 32 * j;
      const float g = float(G[r * NE + e]);
      prob[j] = 1.0f / (1.0f + metal::exp(-g));
      sel[j] = prob[j] + bias[e];
    }
    float total = 0.0f;
    float picked[K];
    for (int k = 0; k < K; k++) {
      float best = -INFINITY;
      int best_e = 1 << 20;
      for (int j = 0; j < NE / 32; j++) {
        const int e = int(lane) + 32 * j;
        if (sel[j] > best) { best = sel[j]; best_e = e; }
      }
      const float top = simd_max(best);
      const int winner = simd_min(best == top ? best_e : (1 << 20));
      float p = 0.0f;
      for (int j = 0; j < NE / 32; j++) {
        if (int(lane) + 32 * j == winner) { p = prob[j]; sel[j] = -INFINITY; }
      }
      p = simd_sum(p);
      picked[k] = p;
      total += p;
      if (lane == 0) { IDX[r * K + k] = uint(winner); ids[r * K + k] = uint(winner); }
    }
    if (lane == 0) {
      const float denominator = total + 1e-20f;
      for (int k = 0; k < K; k++) WT[r * K + k] = picked[k] / denominator * scaling[0];
    }
  }
  threadgroup_barrier(mem_flags::mem_threadgroup);
  const int e = int(t);
  int count = 0;
  if (e < NE)
    for (int p = 0; p < P; p++) count += int(ids[p]) == e ? 1 : 0;
  const int used = count > 0 ? 1 : 0;
  const int pairs_before = simd_prefix_exclusive_sum(count);
  const int used_before = simd_prefix_exclusive_sum(used);
  if (lane == 31) { sg_pairs[sg] = pairs_before + count; sg_used[sg] = used_before + used; }
  threadgroup_barrier(mem_flags::mem_threadgroup);
  int start = pairs_before, u = used_before;
  for (uint q = 0; q < sg; q++) { start += sg_pairs[q]; u += sg_used[q]; }
  if (used) {
    UIDS[u] = uint(e);
    START[u] = start;
    COUNT[u] = count;
    int m = start;
    for (int p = 0; p < P; p++)
      if (int(ids[p]) == e) MEMBERS[m++] = p;
  }
  if (int(t) == T - 1) UCOUNT[0] = u + used;

}
