// Generated by tools/zig/gen_glm_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
namespace metal {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(exp(float(v))); }
namespace fast {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(metal::fast::abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(metal::fast::exp(float(v))); }
}
namespace precise {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(metal::precise::abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(metal::precise::exp(float(v))); }
}
}

inline float load16(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
inline float qdot16(const device uint8_t* w, const thread float* xt, float scale, float bias, float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  return scale * accum + sum * bias;
}

inline float bfsum4(const device bfloat* x) {
  return float(bfloat(float(bfloat(float(bfloat(float(x[0]) + float(x[1]))) + float(x[2]))) + float(x[3])));
}
inline float bfsum8(const device bfloat* x) {
  bfloat s = bfloat(float(x[0]) + float(x[1]));
  s = bfloat(float(s) + float(x[2])); s = bfloat(float(s) + float(x[3])); s = bfloat(float(s) + float(x[4]));
  s = bfloat(float(s) + float(x[5])); s = bfloat(float(s) + float(x[6])); s = bfloat(float(s) + float(x[7]));
  return float(s);
}
template <int B, int V> inline float loadv(const device bfloat* x, thread float* xt);
template <> inline float loadv<4, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
template <> inline float loadv<8, 8>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 8; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<8, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<8, 32>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 32; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<6, 8>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 8; i += 4) {
    sum += bfsum4(x + i);
    xt[i] = float(x[i]); xt[i + 1] = float(x[i + 1]) / 64.0f; xt[i + 2] = float(x[i + 2]) / 16.0f;
    xt[i + 3] = float(x[i + 3]) / 4.0f;
  }
  return sum;
}
template <> inline float loadv<5, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 8) {
    sum += bfsum8(x + i);
    xt[i] = float(x[i]); xt[i + 1] = float(x[i + 1]) / 32.0f; xt[i + 2] = float(x[i + 2]) / 4.0f;
    xt[i + 3] = float(x[i + 3]) / 128.0f; xt[i + 4] = float(x[i + 4]) / 16.0f; xt[i + 5] = float(x[i + 5]) / 2.0f;
    xt[i + 6] = float(x[i + 6]) / 64.0f; xt[i + 7] = float(x[i + 7]) / 8.0f;
  }
  return sum;
}
template <int B, int V> inline float qdotv(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                           float sum);
template <> inline float qdotv<4, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 8>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                     float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 8; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 16; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 32>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 32; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<6, 8>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                     float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 2; i++) {
    xt += 4 * i;
    w += 3 * i;
    accum += (w[0] & 0x3f) * xt[0];
    accum += (w[0] & 0xc0) * xt[1];
    accum += (w[1] & 0x0f) * (xt[1] * 256.0f);
    accum += (w[1] & 0xf0) * xt[2];
    accum += (w[2] & 0x03) * (xt[2] * 256.0f);
    accum += (w[2] & 0xfc) * xt[3];
  }
  return scale * accum + sum * bias;
}
template <> inline float qdotv<5, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 2; i++) {
    xt += 8 * i;
    w += 5 * i;
    accum += (w[0] & 0x1f) * xt[0];
    accum += (w[0] & 0xe0) * xt[1];
    accum += (w[1] & 0x3) * (xt[1] * 256.0f);
    accum += (w[1] & 0x7c) * xt[2];
    accum += (w[1] & 0x80) * xt[3];
    accum += (w[2] & 0xf) * (xt[3] * 256.0f);
    accum += (w[2] & 0xf0) * xt[4];
    accum += (w[3] & 0x1) * (xt[4] * 256.0f);
    accum += (w[3] & 0x3e) * xt[5];
    accum += (w[3] & 0xc0) * xt[6];
    accum += (w[4] & 0x7) * (xt[6] * 256.0f);
    accum += (w[4] & 0xf8) * xt[7];
  }
  return scale * accum + sum * bias;
}

template <typename U>
inline U sigmoid_precise(U x) {
  U e = static_cast<U>(metal::precise::exp(metal::abs(x)));
  U y = static_cast<U>(1) / (static_cast<U>(1) + e);
  return (x < 0) ? y : (static_cast<U>(1) - y);
}
template <typename U>
inline U sigmoid_fast(U x) {
  U e = static_cast<U>(metal::exp(metal::abs(x)));
  U y = static_cast<U>(1) / (static_cast<U>(1) + e);
  return (x < 0) ? y : (static_cast<U>(1) - y);
}
#pragma clang fp contract(off)
template <int FMA>
inline float sq_acc(float acc, float v) { return FMA ? fma(v, v, acc) : v * v + acc; }
inline float mul_add(float acc, float a, float b) { return a * b + acc; }
inline float add_nc(float a, float b) { return a + b; }
#pragma clang fp contract(on)
template <int D, int EXPAND, int SPLIT, int ZOUT, int SQ_FMA>
[[kernel]] void custom_kernel_tf_glm5_fused_hc_expand_cc77af98f2__4096_1_0_0_0_bfloat16_t_bfloat16_t_float_float_floatc_bfloat16_t_float_float(
  const device bfloat16_t* XOLD [[buffer(0)]],
  const device bfloat16_t* BRANCH [[buffer(1)]],
  const device float* POST [[buffer(2)]],
  const device float* COMB [[buffer(3)]],
  const constant float* EPS [[buffer(4)]],
  device bfloat16_t* XNEW [[buffer(5)]],
  device float* INV [[buffer(6)]],
  device float* Z [[buffer(7)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 thread_position_in_threadgroup [[thread_position_in_threadgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {

  constexpr int S = 4;
  constexpr int F = S * D;
  constexpr int MIX = (2 + S) * S;

  const int r = int(threadgroup_position_in_grid.x);
  const uint t = thread_position_in_threadgroup.x;
  const uint lane = thread_index_in_simdgroup, sg = simdgroup_index_in_threadgroup;
  threadgroup float red[32];
  threadgroup float inv_s[1];
  device const bfloat* xo = XOLD + size_t(r) * F;
  device bfloat* xn = XNEW + size_t(r) * F;
  float ss = 0.0f;
  float vals[F / 1024];
  for (int k = 0; k < F / 4096; ++k) {
    for (int i = 0; i < 4; ++i) {
      const int f = int(t) * 4 + 4096 * k + i;
      float v;
      if (EXPAND) {
        const int s = f / D, d = f - s * D;
        const float y = POST[r * S + s] * float(BRANCH[size_t(r) * D + d]);
        const device float* c = COMB + r * S * S;
        float mm = c[0 * S + s] * float(xo[0 * D + d]);
        mm = fma(c[1 * S + s], float(xo[1 * D + d]), mm);
        mm = fma(c[2 * S + s], float(xo[2 * D + d]), mm);
        mm = fma(c[3 * S + s], float(xo[3 * D + d]), mm);
        const bfloat nb = bfloat(add_nc(y, mm));
        xn[f] = nb;
        v = float(nb);
      } else {
        v = float(xo[f]);
      }
      vals[k * 4 + i] = v;
      ss = sq_acc<SQ_FMA>(ss, v);
    }
  }
  if (!SPLIT) return;
  ss = simd_sum(ss);
  if (sg == 0) red[lane] = 0.0f;
  threadgroup_barrier(mem_flags::mem_threadgroup);
  if (lane == 0) red[sg] = ss;
  threadgroup_barrier(mem_flags::mem_threadgroup);
  if (sg == 0) {
    const float a = simd_sum(red[lane]);
    if (lane == 0) {
      const float inv = metal::precise::rsqrt(a / float(F) + EPS[0]);
      INV[r] = inv;
      inv_s[0] = inv;
    }
  }
  if (!ZOUT) return;
  threadgroup_barrier(mem_flags::mem_threadgroup);
  const float inv = inv_s[0];
  device float* z = Z + size_t(r) * F;
  for (int k = 0; k < F / 4096; ++k)
    for (int i = 0; i < 4; ++i) z[int(t) * 4 + 4096 * k + i] = vals[k * 4 + i] * inv;

}

template [[host_name("custom_kernel_tf_glm5_fused_hc_expand_cc77af98f2__4096_1_0_0_0_bfloat16_t_bfloat16_t_float_float_floatc_bfloat16_t_float_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_hc_expand_cc77af98f2__4096_1_0_0_0_bfloat16_t_bfloat16_t_float_float_floatc_bfloat16_t_float_float<4096, 1, 0, 0, 0>) custom_kernel_tf_glm5_fused_hc_expand_cc77af98f2__4096_1_0_0_0_bfloat16_t_bfloat16_t_float_float_floatc_bfloat16_t_float_float<4096, 1, 0, 0, 0>;
