// Generated by tools/zig/gen_glm_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
namespace metal {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(exp(float(v))); }
namespace fast {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(metal::fast::abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(metal::fast::exp(float(v))); }
}
namespace precise {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(metal::precise::abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(metal::precise::exp(float(v))); }
}
}

template <int BITS, int PER>
inline float quad_dot(device const bfloat* x, device const uint8_t* wb, float s, float bb);
template <>
inline float quad_dot<4, 32>(device const bfloat* x, device const uint8_t* wb, float s, float bb) {
  constexpr int PER = 32;
  float xt[PER];
  float sum = 0.0f;
  for (int i = 0; i < PER; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], e = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(e)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(e) / 4096.0f;
  }
  device const uint16_t* ws = (device const uint16_t*)wb;
  float accum = 0.0f;
  for (int i = 0; i < PER / 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  float result = 0.0f;
  result += s * accum + sum * bb;
  return result;
}
template <>
inline float quad_dot<4, 16>(device const bfloat* x, device const uint8_t* wb, float s, float bb) {
  constexpr int PER = 16;
  float xt[PER];
  float sum = 0.0f;
  for (int i = 0; i < PER; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], e = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(e)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(e) / 4096.0f;
  }
  device const uint16_t* ws = (device const uint16_t*)wb;
  float accum = 0.0f;
  for (int i = 0; i < PER / 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  float result = 0.0f;
  result += s * accum + sum * bb;
  return result;
}
template <>
inline float quad_dot<8, 32>(device const bfloat* x, device const uint8_t* wb, float s, float bb) {
  constexpr int PER = 32;
  float xt[PER];
  float sum = 0.0f;
  for (int i = 0; i < PER; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  float accum = 0.0f;
  for (int i = 0; i < PER; i++) accum += xt[i] * wb[i];
  float result = 0.0f;
  result += s * accum + sum * bb;
  return result;
}
template <>
inline float quad_dot<8, 16>(device const bfloat* x, device const uint8_t* wb, float s, float bb) {
  constexpr int PER = 16;
  float xt[PER];
  float sum = 0.0f;
  for (int i = 0; i < PER; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  float accum = 0.0f;
  for (int i = 0; i < PER; i++) accum += xt[i] * wb[i];
  float result = 0.0f;
  result += s * accum + sum * bb;
  return result;
}
template <typename U>
inline U mlx_sigmoid_precise(U x) {
  U e = static_cast<U>(metal::precise::exp(metal::abs(x)));
  U y = static_cast<U>(1) / (static_cast<U>(1) + e);
  return (x < 0) ? y : (static_cast<U>(1) - y);
}
#pragma clang fp contract(off)
inline float sq_acc(float acc, float v) {
  return v * v + acc;
}
#pragma clang fp contract(on)
template <int H, int D, int TAPS, int TY, int FB, int GB>
[[kernel]] void custom_kernel_tf_glm5_kda_rows_918a341e71__64_128_4_32_4_4_bfloat16_t_bfloat16_t_float_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_float_float_float_float_floatc_floatc_bfloat16_t_float_bfloat16_t(
  const device bfloat16_t* P [[buffer(0)]],
  const constant int* P_shape [[buffer(1)]],
  const device bfloat16_t* CS [[buffer(2)]],
  const device float* CW [[buffer(3)]],
  const device uint32_t* FBW [[buffer(4)]],
  const device bfloat16_t* FBS [[buffer(5)]],
  const device bfloat16_t* FBB [[buffer(6)]],
  const device uint32_t* GBW [[buffer(7)]],
  const device bfloat16_t* GBS [[buffer(8)]],
  const device bfloat16_t* GBB [[buffer(9)]],
  const device float* A [[buffer(10)]],
  const device float* DTB [[buffer(11)]],
  const device float* ST [[buffer(12)]],
  const device float* ONW [[buffer(13)]],
  const constant float* LB [[buffer(14)]],
  const constant float* EPS [[buffer(15)]],
  device bfloat16_t* Y [[buffer(16)]],
  device float* ST_OUT [[buffer(17)]],
  device bfloat16_t* CS_OUT [[buffer(18)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_threadgroup [[thread_index_in_threadgroup]],
  uint3 thread_position_in_threadgroup [[thread_position_in_threadgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {

  const uint h    = threadgroup_position_in_grid.z;
  const uint lane = thread_position_in_threadgroup.x;
  const uint ty   = thread_position_in_threadgroup.y;
  const uint tid  = thread_index_in_threadgroup;
  constexpr int NT   = 32 * TY;
  constexpr int NDK  = D / 32;
  constexpr int NDV  = D / TY;
  constexpr int RBLK = D / 128;
  constexpr int REXTRA = D - RBLK * 128;
  constexpr uint W   = (uint)(H * D);
  constexpr uint C3  = 3u * W;
  constexpr uint FA  = C3;
  constexpr uint GA  = C3 + (uint)D;
  constexpr uint BO  = C3 + 2u * (uint)D;
  const int R = int(P_shape[0]);
  const uint PS = (uint)P_shape[1];

  threadgroup float sq[D];
  threadgroup float sk[D];
  threadgroup float sv[D];
  threadgroup float sa[D];
  threadgroup float sg[D];
  threadgroup float sgate[D];
  threadgroup float sy[D];
  threadgroup float shr[3];

  device const float* si = ST + (size_t)h * D * D;
  float st[NDV][NDK];
  for (int j = 0; j < NDV; ++j) {
    uint dv = ty + (uint)TY * (uint)j;
    for (int i = 0; i < NDK; ++i) st[j][i] = si[(size_t)dv * D + NDK * lane + i];
  }
  const float a_h = A[h];
  const float lb = LB[0];
  const float eps = EPS[0];

  for (int r = 0; r < R; ++r) {
    device const bfloat* prow = P + (size_t)r * PS;
    {
      constexpr int PER = D / 4;
      constexpr int KG = D / 64;
      constexpr int FKB = D * FB / 8;
      constexpr int GKB = D * GB / 8;
      const uint q_id = tid / 4u, qlid = tid % 4u;
      for (uint t = q_id; t < 2u * (uint)D; t += (uint)(NT / 4)) {
        const uint proj = t / (uint)D;
        const uint d = t - proj * (uint)D;
        const uint row = h * (uint)D + d;
        device const bfloat* x = prow + (proj == 0u ? FA : GA) + qlid * (uint)PER;
        const uint gi = row * (uint)KG + qlid / (uint)(64 / PER);
        const float s = float(proj == 0u ? FBS[gi] : GBS[gi]);
        const float bb = float(proj == 0u ? FBB[gi] : GBB[gi]);
        float result;
        if (proj == 0u) {
          device const uint8_t* wb = (device const uint8_t*)FBW + (size_t)row * FKB + qlid * (PER * FB / 8);
          result = quad_dot<FB, PER>(x, wb, s, bb);
        } else {
          device const uint8_t* wb = (device const uint8_t*)GBW + (size_t)row * GKB + qlid * (PER * GB / 8);
          result = quad_dot<GB, PER>(x, wb, s, bb);
        }
        const float v = quad_sum(result);
        if (qlid == 0u) {
          if (proj == 0u) sa[d] = float(bfloat(v));
          else            sgate[d] = float(bfloat(v));
        }
      }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint idx = tid; idx < 3u * (uint)D; idx += NT) {
      const uint part = idx / (uint)D;
      const uint d = idx - part * (uint)D;
      const uint c = part * W + h * (uint)D + d;
      float acc = 0.0f;
      for (int j = 0; j < TAPS; ++j) {
        const int e = r + j;
        const bfloat xv = e < TAPS - 1 ? CS[(size_t)e * C3 + c] : P[(size_t)(e - (TAPS - 1)) * PS + c];
        const float term = float(xv) * CW[(size_t)j * C3 + c];
        acc = j == 0 ? term : acc + term;
      }
      const bfloat xb = bfloat(acc);
      const bfloat sl = xb * mlx_sigmoid_precise<bfloat>(xb);
      if (part == 0u) sq[d] = float(sl);
      else if (part == 1u) sk[d] = float(sl);
      else sv[d] = float(sl);
    }
    for (uint d = tid; d < (uint)D; d += NT) {
      const float av = float(bfloat(sa[d])) + DTB[h * (uint)D + d];
      sg[d] = metal::precise::exp(lb * mlx_sigmoid_precise<float>(a_h * av));
    }
    if (tid == 0u) shr[2] = float(mlx_sigmoid_precise<bfloat>(prow[BO + h]));
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (simdgroup_index_in_threadgroup == 0u) {
      float pq = 0.0f, pk = 0.0f;
      for (int blk = 0; blk < RBLK; ++blk) {
        const uint base = (uint)(blk * 128) + 4u * lane;
        for (int i = 0; i < 4; ++i) { pq = sq_acc(pq, sq[base + i]); pk = sq_acc(pk, sk[base + i]); }
      }
      for (int i = 0; 4u * lane + (uint)i < (uint)REXTRA && i < 4; ++i) {
        const uint at = (uint)(RBLK * 128) + 4u * lane + (uint)i;
        pq = sq_acc(pq, sq[at]); pk = sq_acc(pk, sk[at]);
      }
      pq = simd_sum(pq);
      pk = simd_sum(pk);
      if (lane == 0u) {
        shr[0] = metal::precise::rsqrt(pq + 1.0e-6f);
        shr[1] = metal::precise::rsqrt(pk + 1.0e-6f);
      }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
      const float rq = shr[0], rk = shr[1];
      const float qscale = metal::precise::rsqrt(float(D));
      for (uint d = tid; d < (uint)D; d += NT) {
        sq[d] = float(bfloat((sq[d] * rq) * qscale));
        sk[d] = float(bfloat(sk[d] * rk));
      }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
      const float beta = shr[2];
      for (int j = 0; j < NDV; ++j) {
        const uint dv = ty + (uint)TY * (uint)j;
        float kv = 0.0f;
        for (int i = 0; i < NDK; ++i) {
          const uint s = NDK * lane + i;
          st[j][i] = st[j][i] * sg[s];
          kv += st[j][i] * sk[s];
        }
        kv = simd_sum(kv);
        const float delta = (sv[dv] - kv) * beta;
        float o = 0.0f;
        for (int i = 0; i < NDK; ++i) {
          const uint s = NDK * lane + i;
          st[j][i] = st[j][i] + sk[s] * delta;
          o += st[j][i] * sq[s];
        }
        o = simd_sum(o);
        if (lane == 0u) sy[dv] = float(bfloat(o));
      }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (simdgroup_index_in_threadgroup == 0u) {
      float po = 0.0f;
      for (int blk = 0; blk < RBLK; ++blk) {
        const uint base = (uint)(blk * 128) + 4u * lane;
        for (int i = 0; i < 4; ++i) po = sq_acc(po, sy[base + i]);
      }
      for (int i = 0; 4u * lane + (uint)i < (uint)REXTRA && i < 4; ++i)
        po = sq_acc(po, sy[(uint)(RBLK * 128) + 4u * lane + (uint)i]);
      po = simd_sum(po);
      if (lane == 0u) shr[0] = metal::precise::rsqrt(po / (float)D + eps);
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
      const float rn = shr[0];
      for (uint d = tid; d < (uint)D; d += NT) {
        float x = sy[d] * rn;
        x = ONW[d] * x;
        x = x * mlx_sigmoid_precise<float>(float(bfloat(sgate[d])));
        Y[(size_t)r * W + h * (uint)D + d] = bfloat(x);
      }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
  }
  device float* so = ST_OUT + (size_t)h * D * D;
  for (int j = 0; j < NDV; ++j) {
    const uint dv = ty + (uint)TY * (uint)j;
    for (int i = 0; i < NDK; ++i) so[(size_t)dv * D + NDK * lane + i] = st[j][i];
  }
  for (uint idx = tid; idx < 3u * (uint)D * (uint)(TAPS - 1); idx += NT) {
    const uint m = idx / (3u * (uint)D);
    const uint rem = idx - m * 3u * (uint)D;
    const uint part = rem / (uint)D;
    const uint d = rem - part * (uint)D;
    const uint c = part * W + h * (uint)D + d;
    const int e = R + int(m);
    CS_OUT[(size_t)m * C3 + c] = e < TAPS - 1 ? CS[(size_t)e * C3 + c] : P[(size_t)(e - (TAPS - 1)) * PS + c];
  }

}

template [[host_name("custom_kernel_tf_glm5_kda_rows_918a341e71__64_128_4_32_4_4_bfloat16_t_bfloat16_t_float_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_float_float_float_float_floatc_floatc_bfloat16_t_float_bfloat16_t")]] [[kernel]] decltype(custom_kernel_tf_glm5_kda_rows_918a341e71__64_128_4_32_4_4_bfloat16_t_bfloat16_t_float_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_float_float_float_float_floatc_floatc_bfloat16_t_float_bfloat16_t<64, 128, 4, 32, 4, 4>) custom_kernel_tf_glm5_kda_rows_918a341e71__64_128_4_32_4_4_bfloat16_t_bfloat16_t_float_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_float_float_float_float_floatc_floatc_bfloat16_t_float_bfloat16_t<64, 128, 4, 32, 4, 4>;
