// Generated by tools/zig/gen_glm_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
namespace metal {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(exp(float(v))); }
namespace fast {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(metal::fast::abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(metal::fast::exp(float(v))); }
}
namespace precise {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(metal::precise::abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(metal::precise::exp(float(v))); }
}
}

inline float load16(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
inline float qdot16(const device uint8_t* w, const thread float* xt, float scale, float bias, float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  return scale * accum + sum * bias;
}

inline float bfsum4(const device bfloat* x) {
  return float(bfloat(float(bfloat(float(bfloat(float(x[0]) + float(x[1]))) + float(x[2]))) + float(x[3])));
}
inline float bfsum8(const device bfloat* x) {
  bfloat s = bfloat(float(x[0]) + float(x[1]));
  s = bfloat(float(s) + float(x[2])); s = bfloat(float(s) + float(x[3])); s = bfloat(float(s) + float(x[4]));
  s = bfloat(float(s) + float(x[5])); s = bfloat(float(s) + float(x[6])); s = bfloat(float(s) + float(x[7]));
  return float(s);
}
template <int B, int V> inline float loadv(const device bfloat* x, thread float* xt);
template <> inline float loadv<4, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
template <> inline float loadv<8, 8>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 8; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<8, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<8, 32>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 32; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<6, 8>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 8; i += 4) {
    sum += bfsum4(x + i);
    xt[i] = float(x[i]); xt[i + 1] = float(x[i + 1]) / 64.0f; xt[i + 2] = float(x[i + 2]) / 16.0f;
    xt[i + 3] = float(x[i + 3]) / 4.0f;
  }
  return sum;
}
template <> inline float loadv<5, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 8) {
    sum += bfsum8(x + i);
    xt[i] = float(x[i]); xt[i + 1] = float(x[i + 1]) / 32.0f; xt[i + 2] = float(x[i + 2]) / 4.0f;
    xt[i + 3] = float(x[i + 3]) / 128.0f; xt[i + 4] = float(x[i + 4]) / 16.0f; xt[i + 5] = float(x[i + 5]) / 2.0f;
    xt[i + 6] = float(x[i + 6]) / 64.0f; xt[i + 7] = float(x[i + 7]) / 8.0f;
  }
  return sum;
}
template <int B, int V> inline float qdotv(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                           float sum);
template <> inline float qdotv<4, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 8>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                     float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 8; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 16; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 32>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 32; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<6, 8>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                     float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 2; i++) {
    xt += 4 * i;
    w += 3 * i;
    accum += (w[0] & 0x3f) * xt[0];
    accum += (w[0] & 0xc0) * xt[1];
    accum += (w[1] & 0x0f) * (xt[1] * 256.0f);
    accum += (w[1] & 0xf0) * xt[2];
    accum += (w[2] & 0x03) * (xt[2] * 256.0f);
    accum += (w[2] & 0xfc) * xt[3];
  }
  return scale * accum + sum * bias;
}
template <> inline float qdotv<5, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 2; i++) {
    xt += 8 * i;
    w += 5 * i;
    accum += (w[0] & 0x1f) * xt[0];
    accum += (w[0] & 0xe0) * xt[1];
    accum += (w[1] & 0x3) * (xt[1] * 256.0f);
    accum += (w[1] & 0x7c) * xt[2];
    accum += (w[1] & 0x80) * xt[3];
    accum += (w[2] & 0xf) * (xt[3] * 256.0f);
    accum += (w[2] & 0xf0) * xt[4];
    accum += (w[3] & 0x1) * (xt[4] * 256.0f);
    accum += (w[3] & 0x3e) * xt[5];
    accum += (w[3] & 0xc0) * xt[6];
    accum += (w[4] & 0x7) * (xt[6] * 256.0f);
    accum += (w[4] & 0xf8) * xt[7];
  }
  return scale * accum + sum * bias;
}

template <typename U>
inline U sigmoid_precise(U x) {
  U e = static_cast<U>(metal::precise::exp(metal::abs(x)));
  U y = static_cast<U>(1) / (static_cast<U>(1) + e);
  return (x < 0) ? y : (static_cast<U>(1) - y);
}
template <typename U>
inline U sigmoid_fast(U x) {
  U e = static_cast<U>(metal::exp(metal::abs(x)));
  U y = static_cast<U>(1) / (static_cast<U>(1) + e);
  return (x < 0) ? y : (static_cast<U>(1) - y);
}
#pragma clang fp contract(off)
template <int FMA>
inline float sq_acc(float acc, float v) { return FMA ? fma(v, v, acc) : v * v + acc; }
inline float mul_add(float acc, float a, float b) { return a * b + acc; }
inline float add_nc(float a, float b) { return a + b; }
#pragma clang fp contract(on)
template <int K, int N, int RPS, int TOPK, int MAXR, int MAXU, int PART, int SB, int SV, int SLB>
[[kernel]] void custom_kernel_tf_glm5_fused_moe_gateup_04bc93a358__4096_1024_4_8_16_128_2_4_16_8_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_int32_t_int32_t_int32_t_floatc_bfloat16_t(
  const device bfloat16_t* X [[buffer(0)]],
  const constant int* X_shape [[buffer(1)]],
  const device uint32_t* GW [[buffer(2)]],
  const device bfloat16_t* GS [[buffer(3)]],
  const device bfloat16_t* GB [[buffer(4)]],
  const device uint32_t* UW [[buffer(5)]],
  const device bfloat16_t* US [[buffer(6)]],
  const device bfloat16_t* UB [[buffer(7)]],
  const device uint32_t* SGU [[buffer(8)]],
  const device bfloat16_t* SGUS [[buffer(9)]],
  const device bfloat16_t* SGUB [[buffer(10)]],
  const device int32_t* UIDS [[buffer(11)]],
  const device int32_t* UMEM [[buffer(12)]],
  const device int32_t* UCOUNT [[buffer(13)]],
  const constant float* LIM [[buffer(14)]],
  device bfloat16_t* ACT [[buffer(15)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {

  const uint lane = thread_index_in_simdgroup;
  const int m = int(simdgroup_index_in_threadgroup);
  if (PART == 1 && SB != 4) {
    constexpr int SBLK = 32 * SV;
    constexpr int SKB = K * SB / 8;
    constexpr int KG1 = K / 64;
    constexpr int SDIV = 64 / SV;
    constexpr int SSTEP = SBLK / 64;
    constexpr int WSTEP = 32 * SLB;
    const int R = int(X_shape[0]);
    if (m >= R) return;
    const int r = m;
    const int row0 = int(threadgroup_position_in_grid.y) * RPS;
    const device uint8_t* gw = (const device uint8_t*)SGU + size_t(row0) * SKB + lane * SLB;
    const device uint8_t* uw = (const device uint8_t*)SGU + size_t(N + row0) * SKB + lane * SLB;
    const device bfloat* gs = SGUS + size_t(row0) * KG1 + lane / SDIV;
    const device bfloat* gb = SGUB + size_t(row0) * KG1 + lane / SDIV;
    const device bfloat* us = SGUS + size_t(N + row0) * KG1 + lane / SDIV;
    const device bfloat* ub = SGUB + size_t(N + row0) * KG1 + lane / SDIV;
    const device bfloat* x = X + size_t(r) * K + lane * SV;
    float ag[RPS], au[RPS];
    for (int j = 0; j < RPS; j++) { ag[j] = 0.0f; au[j] = 0.0f; }
    for (int k0 = 0; k0 < K; k0 += SBLK) {
      float xt[SV];
      const float sum = loadv<SB, SV>(x, xt);
      for (int j = 0; j < RPS; j++) {
        ag[j] += qdotv<SB, SV>(gw + j * SKB, xt, float(gs[j * KG1]), float(gb[j * KG1]), sum);
        au[j] += qdotv<SB, SV>(uw + j * SKB, xt, float(us[j * KG1]), float(ub[j * KG1]), sum);
      }
      gw += WSTEP; uw += WSTEP; gs += SSTEP; gb += SSTEP; us += SSTEP; ub += SSTEP; x += SBLK;
    }
    for (int j = 0; j < RPS; j++) {
      const float gv = simd_sum(ag[j]), uv = simd_sum(au[j]);
      if (lane == 0) {
        const float lim = float(bfloat(LIM[0]));
        const bfloat gt = bfloat(metal::min(float(bfloat(gv)), lim));
        const bfloat up = bfloat(metal::min(metal::max(float(bfloat(uv)), -lim), lim));
        const bfloat sl = gt * sigmoid_fast(gt);
        ACT[size_t(r) * N + row0 + j] = sl * up;
      }
    }
    return;
  }
  const int u = PART == 1 ? MAXU : int(threadgroup_position_in_grid.z);
  const int R = int(X_shape[0]);
  constexpr int SLOTS = PART == 0 ? TOPK + 1 : (PART == 1 ? 1 : TOPK);
  const bool shared = u == MAXU;
  if (!shared && u >= UCOUNT[0]) return;
  const int pick = shared ? (m < R ? m * TOPK : -1) : UMEM[u * MAXR + m];
  if (pick < 0) return;
  const int r = pick / TOPK, slot = shared ? (PART == 1 ? 0 : TOPK) : pick % TOPK;
  const int row0 = int(threadgroup_position_in_grid.y) * RPS;
  constexpr int KB = K / 2;
  constexpr int KG = K / 64;
  const size_t e = shared ? 0 : size_t(UIDS[u]);
  const size_t grow = shared ? size_t(row0) : e * N + row0;
  const size_t urow = shared ? size_t(N + row0) : e * N + row0;
  const device uint8_t* gw = (const device uint8_t*)(shared ? SGU : GW) + grow * KB + lane * 8;
  const device uint8_t* uw = (const device uint8_t*)(shared ? SGU : UW) + urow * KB + lane * 8;
  const device bfloat* gs = (shared ? SGUS : GS) + grow * KG + lane / 4;
  const device bfloat* gb = (shared ? SGUB : GB) + grow * KG + lane / 4;
  const device bfloat* us = (shared ? SGUS : US) + urow * KG + lane / 4;
  const device bfloat* ub = (shared ? SGUB : UB) + urow * KG + lane / 4;
  const device bfloat* x = X + size_t(r) * K + lane * 16;
  float ag[RPS], au[RPS];
  for (int j = 0; j < RPS; j++) { ag[j] = 0.0f; au[j] = 0.0f; }
  for (int k0 = 0; k0 < K; k0 += 512) {
    float xt[16];
    const float sum = load16(x, xt);
    for (int j = 0; j < RPS; j++) {
      ag[j] += qdot16(gw + j * KB, xt, float(gs[j * KG]), float(gb[j * KG]), sum);
      au[j] += qdot16(uw + j * KB, xt, float(us[j * KG]), float(ub[j * KG]), sum);
    }
    gw += 256; uw += 256; gs += 8; gb += 8; us += 8; ub += 8; x += 512;
  }
  for (int j = 0; j < RPS; j++) {
    const float gv = simd_sum(ag[j]), uv = simd_sum(au[j]);
    if (lane == 0) {
      const float lim = float(bfloat(LIM[0]));
      const bfloat gt = bfloat(metal::min(float(bfloat(gv)), lim));
      const bfloat up = bfloat(metal::min(metal::max(float(bfloat(uv)), -lim), lim));
      const bfloat sl = gt * sigmoid_fast(gt);
      ACT[(size_t(r) * SLOTS + slot) * N + row0 + j] = sl * up;
    }
  }

}

template [[host_name("custom_kernel_tf_glm5_fused_moe_gateup_04bc93a358__4096_1024_4_8_16_128_2_4_16_8_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_int32_t_int32_t_int32_t_floatc_bfloat16_t")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_moe_gateup_04bc93a358__4096_1024_4_8_16_128_2_4_16_8_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_int32_t_int32_t_int32_t_floatc_bfloat16_t<4096, 1024, 4, 8, 16, 128, 2, 4, 16, 8>) custom_kernel_tf_glm5_fused_moe_gateup_04bc93a358__4096_1024_4_8_16_128_2_4_16_8_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_int32_t_int32_t_int32_t_floatc_bfloat16_t<4096, 1024, 4, 8, 16, 128, 2, 4, 16, 8>;
