// Generated by tools/zig/gen_glm_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
namespace metal {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(exp(float(v))); }
namespace fast {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(metal::fast::abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(metal::fast::exp(float(v))); }
}
namespace precise {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(metal::precise::abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(metal::precise::exp(float(v))); }
}
}

inline float load16(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
inline float qdot16(const device uint8_t* w, const thread float* xt, float scale, float bias, float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  return scale * accum + sum * bias;
}
template <int K, int N, int RPS>
[[kernel]] void custom_kernel_tf_glm5_qmv_rows64_c8929b27db__4096_12288_4_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_bfloat16_t(
  const device bfloat16_t* X [[buffer(0)]],
  const device uint32_t* W [[buffer(1)]],
  const device bfloat16_t* S [[buffer(2)]],
  const device bfloat16_t* B [[buffer(3)]],
  device bfloat16_t* OUT [[buffer(4)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {

  const uint lane = thread_index_in_simdgroup;
  const int r = int(simdgroup_index_in_threadgroup);
  const int row0 = int(threadgroup_position_in_grid.y) * RPS;
  constexpr int KB = K / 2;
  constexpr int KG = K / 64;
  const device uint8_t* w = (const device uint8_t*)W + size_t(row0) * KB + lane * 8;
  const device bfloat* sc = S + size_t(row0) * KG + lane / 4;
  const device bfloat* bi = B + size_t(row0) * KG + lane / 4;
  const device bfloat* x = X + r * K + lane * 16;
  float acc[RPS];
  for (int j = 0; j < RPS; j++) acc[j] = 0.0f;
  for (int k0 = 0; k0 < K; k0 += 512) {
    float xt[16];
    const float sum = load16(x, xt);
    for (int j = 0; j < RPS; j++)
      acc[j] += qdot16(w + j * KB, xt, float(sc[j * KG]), float(bi[j * KG]), sum);
    w += 256; sc += 8; bi += 8; x += 512;
  }
  for (int j = 0; j < RPS; j++) {
    const float v = simd_sum(acc[j]);
    if (lane == 0) OUT[r * N + row0 + j] = bfloat(v);
  }

}

template [[host_name("custom_kernel_tf_glm5_qmv_rows64_c8929b27db__4096_12288_4_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_bfloat16_t")]] [[kernel]] decltype(custom_kernel_tf_glm5_qmv_rows64_c8929b27db__4096_12288_4_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_bfloat16_t<4096, 12288, 4>) custom_kernel_tf_glm5_qmv_rows64_c8929b27db__4096_12288_4_bfloat16_t_uint32_t_bfloat16_t_bfloat16_t_bfloat16_t<4096, 12288, 4>;
