// Generated by tools/zig/gen_glm_kernels.py from our Python kernels; do not edit.
#include <metal_stdlib>
using namespace metal;
typedef bfloat bfloat16_t;
typedef half float16_t;
namespace metal {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(exp(float(v))); }
namespace fast {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(metal::fast::abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(metal::fast::exp(float(v))); }
}
namespace precise {
inline bfloat16_t abs(bfloat16_t v) { return bfloat16_t(metal::precise::abs(float(v))); }
inline bfloat16_t exp(bfloat16_t v) { return bfloat16_t(metal::precise::exp(float(v))); }
}
}

inline float load16(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
inline float qdot16(const device uint8_t* w, const thread float* xt, float scale, float bias, float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  return scale * accum + sum * bias;
}

inline float bfsum4(const device bfloat* x) {
  return float(bfloat(float(bfloat(float(bfloat(float(x[0]) + float(x[1]))) + float(x[2]))) + float(x[3])));
}
inline float bfsum8(const device bfloat* x) {
  bfloat s = bfloat(float(x[0]) + float(x[1]));
  s = bfloat(float(s) + float(x[2])); s = bfloat(float(s) + float(x[3])); s = bfloat(float(s) + float(x[4]));
  s = bfloat(float(s) + float(x[5])); s = bfloat(float(s) + float(x[6])); s = bfloat(float(s) + float(x[7]));
  return float(s);
}
template <int B, int V> inline float loadv(const device bfloat* x, thread float* xt);
template <> inline float loadv<4, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 4) {
    const bfloat a = x[i], b = x[i + 1], c = x[i + 2], d = x[i + 3];
    sum += float(bfloat(float(bfloat(float(bfloat(float(a) + float(b))) + float(c))) + float(d)));
    xt[i] = float(a); xt[i + 1] = float(b) / 16.0f; xt[i + 2] = float(c) / 256.0f; xt[i + 3] = float(d) / 4096.0f;
  }
  return sum;
}
template <> inline float loadv<8, 8>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 8; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<8, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<8, 32>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 32; i++) { sum += float(x[i]); xt[i] = float(x[i]); }
  return sum;
}
template <> inline float loadv<6, 8>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 8; i += 4) {
    sum += bfsum4(x + i);
    xt[i] = float(x[i]); xt[i + 1] = float(x[i + 1]) / 64.0f; xt[i + 2] = float(x[i + 2]) / 16.0f;
    xt[i + 3] = float(x[i + 3]) / 4.0f;
  }
  return sum;
}
template <> inline float loadv<5, 16>(const device bfloat* x, thread float* xt) {
  float sum = 0.0f;
  for (int i = 0; i < 16; i += 8) {
    sum += bfsum8(x + i);
    xt[i] = float(x[i]); xt[i + 1] = float(x[i + 1]) / 32.0f; xt[i + 2] = float(x[i + 2]) / 4.0f;
    xt[i + 3] = float(x[i + 3]) / 128.0f; xt[i + 4] = float(x[i + 4]) / 16.0f; xt[i + 5] = float(x[i + 5]) / 2.0f;
    xt[i + 6] = float(x[i + 6]) / 64.0f; xt[i + 7] = float(x[i + 7]) / 8.0f;
  }
  return sum;
}
template <int B, int V> inline float qdotv(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                           float sum);
template <> inline float qdotv<4, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  const device uint16_t* ws = (const device uint16_t*)w;
  float accum = 0.0f;
  for (int i = 0; i < 4; i++)
    accum += xt[4 * i] * float(ws[i] & 0x000f) + xt[4 * i + 1] * float(ws[i] & 0x00f0) +
             xt[4 * i + 2] * float(ws[i] & 0x0f00) + xt[4 * i + 3] * float(ws[i] & 0xf000);
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 8>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                     float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 8; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 16; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<8, 32>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 32; i++) accum += xt[i] * w[i];
  return scale * accum + sum * bias;
}
template <> inline float qdotv<6, 8>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                     float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 2; i++) {
    xt += 4 * i;
    w += 3 * i;
    accum += (w[0] & 0x3f) * xt[0];
    accum += (w[0] & 0xc0) * xt[1];
    accum += (w[1] & 0x0f) * (xt[1] * 256.0f);
    accum += (w[1] & 0xf0) * xt[2];
    accum += (w[2] & 0x03) * (xt[2] * 256.0f);
    accum += (w[2] & 0xfc) * xt[3];
  }
  return scale * accum + sum * bias;
}
template <> inline float qdotv<5, 16>(const device uint8_t* w, const thread float* xt, float scale, float bias,
                                      float sum) {
  float accum = 0.0f;
  for (int i = 0; i < 2; i++) {
    xt += 8 * i;
    w += 5 * i;
    accum += (w[0] & 0x1f) * xt[0];
    accum += (w[0] & 0xe0) * xt[1];
    accum += (w[1] & 0x3) * (xt[1] * 256.0f);
    accum += (w[1] & 0x7c) * xt[2];
    accum += (w[1] & 0x80) * xt[3];
    accum += (w[2] & 0xf) * (xt[3] * 256.0f);
    accum += (w[2] & 0xf0) * xt[4];
    accum += (w[3] & 0x1) * (xt[4] * 256.0f);
    accum += (w[3] & 0x3e) * xt[5];
    accum += (w[3] & 0xc0) * xt[6];
    accum += (w[4] & 0x7) * (xt[6] * 256.0f);
    accum += (w[4] & 0xf8) * xt[7];
  }
  return scale * accum + sum * bias;
}

template <typename U>
inline U sigmoid_precise(U x) {
  U e = static_cast<U>(metal::precise::exp(metal::abs(x)));
  U y = static_cast<U>(1) / (static_cast<U>(1) + e);
  return (x < 0) ? y : (static_cast<U>(1) - y);
}
template <typename U>
inline U sigmoid_fast(U x) {
  U e = static_cast<U>(metal::exp(metal::abs(x)));
  U y = static_cast<U>(1) / (static_cast<U>(1) + e);
  return (x < 0) ? y : (static_cast<U>(1) - y);
}
#pragma clang fp contract(off)
template <int FMA>
inline float sq_acc(float acc, float v) { return FMA ? fma(v, v, acc) : v * v + acc; }
inline float mul_add(float acc, float a, float b) { return a * b + acc; }
inline float add_nc(float a, float b) { return a + b; }
#pragma clang fp contract(on)
template <int K, int NE, int RR, int C, int NT>
[[kernel]] void custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float(
  const device float* X [[buffer(0)]],
  const device bfloat16_t* RP [[buffer(1)]],
  device float* OUT [[buffer(2)]],
  uint simdgroup_index_in_threadgroup [[simdgroup_index_in_threadgroup]],
  uint thread_index_in_simdgroup [[thread_index_in_simdgroup]],
  uint3 thread_position_in_threadgroup [[thread_position_in_threadgroup]],
  uint3 threadgroup_position_in_grid [[threadgroup_position_in_grid]]) {

  const uint t = thread_position_in_threadgroup.x;
  const uint lane = thread_index_in_simdgroup, sg = simdgroup_index_in_threadgroup;
  const int thrM = int(lane) / 4, thrN = int(lane) % 4;
  const int g = int(threadgroup_position_in_grid.x);
  constexpr int ITERS = K / 32;
  constexpr int NCH = ITERS / C;
  constexpr int UNITS = 32 * C * 2;
  constexpr int XS = 32 * C;
  threadgroup uint4 buf[2][UNITS];
  threadgroup float xb[2][RR][XS];
  const device uint4* rp = (const device uint4*)RP;
  auto fetch = [&](int ch, int b) {
    for (int u = int(t) - 32; u < UNITS + RR * XS; u += int(NT) - 32) {
      if (u < 0) continue;
      if (u < UNITS) {
        const int l = u / (C * 2), it = (u % (C * 2)) / 2, hh = u % 2;
        const int q = g * 4 + (l % 4), m = l / 4;
        buf[b][u] = rp[((size_t(q) * 8 + m) * ITERS + ch * C + it) * 2 + hh];
      } else {
        const int v = u - UNITS, r = v / XS, k = v % XS;
        xb[b][r][k] = X[size_t(r) * K + ch * XS + k];
      }
    }
  };
  float acc[RR][4];
  for (int r = 0; r < RR; r++) for (int tn = 0; tn < 4; tn++) acc[r][tn] = 0.0f;
  fetch(0, 0);
  threadgroup_barrier(mem_flags::mem_threadgroup);
  for (int ch = 0; ch < NCH; ch++) {
    const int b = ch & 1;
    if (sg != 0) {
      if (ch + 1 < NCH) fetch(ch + 1, b ^ 1);
    } else {
      for (int it = 0; it < C; it++) {
        float inter[4][4];
        for (int h = 0; h < 2; h++) {
          const uint4 v = buf[b][(int(lane) * C + it) * 2 + h];
          const uint words[4] = {v.x, v.y, v.z, v.w};
          for (int j = 0; j < 4; j++) {
            const int e = h * 8 + j * 2;
            inter[e / 4][e % 4] = as_type<float>(words[j] << 16);
            inter[(e + 1) / 4][(e + 1) % 4] = as_type<float>(words[j] & 0xffff0000u);
          }
        }
        const int bm = 4 * thrM + 32 * it;
        for (int r = 0; r < RR; r++) {
          float vc[4];
          for (int tm = 0; tm < 4; tm++) vc[tm] = xb[b][r][bm + tm];
          for (int tm = 0; tm < 4; tm++)
            for (int tn = 0; tn < 4; tn++) acc[r][tn] += vc[tm] * inter[tm][tn];
        }
      }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
  }
  if (sg != 0) return;
  const int q = g * 4 + thrN;
  for (int r = 0; r < RR; r++)
    for (int tn = 0; tn < 4; tn++) {
      float v = acc[r][tn];
      for (ushort sm = 4; sm >= 1; sm >>= 1) v += simd_shuffle_down(v, 4 * sm);
      if (thrM == 0) OUT[size_t(r) * NE + 4 * q + tn] = v;
    }

}

template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 1, 8, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 1, 8, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_2_8_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 2, 8, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 2, 8, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_3_8_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 3, 8, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 3, 8, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_4_8_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 4, 8, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 4, 8, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_5_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 5, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 5, 4, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_6_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 6, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 6, 4, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_7_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 7, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 7, 4, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_8_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 8, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 8, 4, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_9_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 9, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 9, 4, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_10_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 10, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 10, 4, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_11_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 11, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 11, 4, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_12_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 12, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 12, 4, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_13_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 13, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 13, 4, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_14_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 14, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 14, 4, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_15_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 15, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 15, 4, 1024>;
template [[host_name("custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_16_4_1024_float_bfloat16_t_float")]] [[kernel]] decltype(custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 16, 4, 1024>) custom_kernel_tf_glm5_fused_router_tg_331f012361__4096_288_1_8_1024_float_bfloat16_t_float<4096, 288, 16, 4, 1024>;
