"""Prefill .metal files (our preamble, a header of inline kernels, generated entry points) and their MLX caller."""

from __future__ import annotations

import os
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from metal_source import PREAMBLE, TYPE_NAMES, Arg, function_name, kernel_text  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
DIR = ROOT / "zig/kernels/metal/prefill"
MARK = "// ---- entry points: generated by tools/zig/check_prefill_ops.py --write ----\n"
SHORT = {"bfloat16": "bf16", "float32": "f32", "int32": "i32", "uint32": "u32"}


def header(file: str) -> str:
    """The hand-written part of a prefill file after our preamble, its local includes inlined as the compiler needs."""

    from check_mlx_ops import with_includes

    text = with_includes(DIR / file)
    first, rest = text.split("\n", 1)
    if not first.startswith("//") or not rest.startswith(PREAMBLE) or MARK not in rest:
        raise ValueError(f"{file}: expected a comment line, our preamble, a header and the entry-point mark")
    return rest[len(PREAMBLE):rest.index(MARK)]


@dataclass(frozen=True)
class Family:
    """A kernel's entry: argument names in binding order, a body formatted with the variant's constants, its attribute."""

    file: str
    name: str
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    body: str
    params: tuple[str, ...]
    threads: int = 0                       # MLX's max_total_threads_per_threadgroup for this kernel (0: none)

    def attr(self) -> str:
        return f"[[max_total_threads_per_threadgroup({self.threads})]]\n" if self.threads else ""


def metal_value(v: object) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    return str(v) if isinstance(v, int) else TYPE_NAMES[str(v)]


@dataclass(frozen=True)
class Variant:
    """One entry point: the family's constants (dtypes as mlx names) and its argument dtypes."""

    family: Family
    values: tuple
    dtypes: tuple[str, ...]                 # inputs then outputs

    def name(self) -> str:
        parts = [("t" if v else "n") if isinstance(v, bool) else SHORT.get(str(v), str(v)) for v in self.values]
        return "_".join([self.family.name, *parts])

    def args(self) -> tuple[list[Arg], list[Arg]]:
        f = self.family
        ins = [Arg(n, d, 1 << 20) for n, d in zip(f.inputs, self.dtypes)]
        outs = [Arg(n, d, 1 << 20) for n, d in zip(f.outputs, self.dtypes[len(f.inputs):])]
        return ins, outs

    def body(self) -> str:
        return self.family.body.format(**{k: metal_value(v) for k, v in zip(self.family.params, self.values)})

    def function(self) -> str:
        ins, outs = self.args()
        return function_name(self.name(), ins, outs, [])

    def text(self) -> str:
        """The text MLX compiles after its preamble: our header, the attribute, the generated kernel."""

        ins, outs = self.args()
        return kernel_text(self.name(), ins, outs, self.body(), header(self.family.file) + self.family.attr())[1]


def entry_text(variants: list[Variant]) -> str:
    """A file's generated entry points: each variant's attribute and kernel, without the header."""

    out = []
    for v in variants:
        h = header(v.family.file)
        t = v.text()
        assert t.startswith(h)
        out.append(t[len(h):])
    return "".join(out)


def write(file: str, variants: list[Variant]) -> bool:
    """Regenerate a file's entry points; True if the file changed."""

    path = DIR / file
    text = path.read_text()
    new = text[:text.index(MARK) + len(MARK)] + entry_text(variants)
    if new != text:
        path.write_text(new)
        return True
    return False


def stale(file: str, variants: list[Variant]) -> bool:
    text = (DIR / file).read_text()
    return text[text.index(MARK) + len(MARK):] != entry_text(variants)


class Runner:
    """mx.fast.metal_kernel objects for variants, built once, with MLX's own text checked against ours once."""

    def __init__(self, mx) -> None:
        self.mx = mx
        self.kernels: dict[str, object] = {}
        self.checked: set[str] = set()

    def kernel(self, v: Variant):
        name = v.name()
        if name not in self.kernels:
            f = v.family
            self.kernels[name] = self.mx.fast.metal_kernel(name=name, input_names=list(f.inputs),
                                                           output_names=list(f.outputs), source=v.body(),
                                                           header=header(f.file) + f.attr())
        return self.kernels[name]

    def __call__(self, v: Variant, inputs: list, grid: tuple, group: tuple, shapes: list, verify: bool = True):
        mx = self.mx
        call = dict(inputs=inputs, grid=tuple(grid), threadgroup=tuple(group), output_shapes=[tuple(s) for s in shapes],
                    output_dtypes=[getattr(mx, d) for d in v.dtypes[len(v.family.inputs):]])
        if verify and v.name() not in self.checked:
            if mlx_text(self.kernel(v), call) != v.text():
                raise SystemExit(f"{v.function()}: MLX's generated text differs from the file's")
            self.checked.add(v.name())
        return self.kernel(v)(**call)


def mlx_text(kernel, call: dict) -> str:
    """The kernel text MLX generates for this call (its verbose print, captured from fd 1)."""

    import mlx.core as mx

    sys.stdout.flush()
    saved = os.dup(1)
    with tempfile.TemporaryFile(mode="w+b") as tmp:
        os.dup2(tmp.fileno(), 1)
        try:
            mx.eval(kernel(**call, verbose=True))
        finally:
            os.dup2(saved, 1)
            os.close(saved)
        tmp.seek(0)
        printed = tmp.read().decode()
    body = printed.split("```\n", 1)[1]
    return body[: body.rindex("\n```")]
