"""Generate zig/src/core/tokenizer/unicode_data.zig from the Unicode Character Database (Python's unicodedata, Perl's Unicode::UCD)."""
import argparse
import subprocess
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
# tokenizers 0.23 matches regex classes on Unicode 16.0 but normalizes with 9.0 tables; tokenizer_parity.py checks both.
VERSION = "16.0.0"
NORMALIZATION = "9.0"
CATEGORIES = ("Cn Lu Ll Lt Lm Lo Mn Mc Me Nd Nl No Pc Pd Ps Pe Pi Pf Po "
              "Sm Sc Sk So Zs Zl Zp Cc Cf Cs Co").split()


def present_in(version):
    """Code points assigned by `version` (UCD Present_In), from Perl's core Unicode::UCD."""
    script = f'print join(",", Unicode::UCD::prop_invlist("Present_In={version}"))'
    bounds = [int(x) for x in subprocess.run(["perl", "-MUnicode::UCD", "-e", script], capture_output=True, text=True,
                                             check=True).stdout.split(",")]
    bounds += [0x110000] * (len(bounds) % 2)
    return {cp for lo, hi in zip(bounds[::2], bounds[1::2]) for cp in range(lo, hi)}


def category_runs():
    runs, last = [], None
    for cp in range(0x110000):
        cat = CATEGORIES.index(unicodedata.category(chr(cp)))
        if cat != last:
            runs.append(cp << 5 | cat)
            last = cat
    return runs


def combining_runs(assigned):
    runs = []
    for cp in sorted(assigned):
        ccc = unicodedata.combining(chr(cp))
        if ccc and runs and runs[-1][1] == cp - 1 and runs[-1][2] == ccc:
            runs[-1][1] = cp
        elif ccc:
            runs.append([cp, cp, ccc])
    return runs


def canonical(assigned):
    decompositions, compositions = [], []
    for cp in sorted(assigned):
        fields = unicodedata.decomposition(chr(cp)).split()
        if not fields or fields[0].startswith("<") or 0xAC00 <= cp <= 0xD7A3:
            continue
        parts = [int(x, 16) for x in fields]
        assert len(parts) <= 2, hex(cp)
        decompositions.append((cp, parts[0], parts[1] if len(parts) == 2 else 0))
        # A two-part mapping composes unless it is a full composition exclusion, which NFC never produces.
        if len(parts) == 2 and unicodedata.normalize("NFC", chr(cp)) == chr(cp):
            compositions.append((parts[0], parts[1], cp))
    compositions.sort()
    return decompositions, compositions


def case_folds():
    single, pairs = [], set()
    for cp in range(0x80, 0x110000):
        folded = chr(cp).casefold()
        if len(folded) == 1 and folded.isascii() and folded != chr(cp):
            single.append((cp, ord(folded)))
        elif len(folded) > 1 and folded.isascii():
            pairs.update(folded[i:i + 2] for i in range(len(folded) - 1))
    return single, sorted(pairs)


def rows(values, per_line, fmt):
    for i in range(0, len(values), per_line):
        yield "    " + " ".join(fmt(v) + "," for v in values[i:i + per_line])


def render():
    assigned = present_in(NORMALIZATION)
    decompositions, compositions = canonical(assigned)
    folds, multi = case_folds()
    triple = lambda t: ".{ " + ", ".join(f"0x{x:05X}" for x in t) + " }"
    out = [f"// Generated by tools/zig/unicode_tables.py from the Unicode {VERSION} character database; do not edit.",
           f'pub const version = "{VERSION}";',
           f'pub const normalization_version = "{NORMALIZATION}";',
           f"pub const categories = [_][]const u8{{ {', '.join(chr(34) + c + chr(34) for c in CATEGORIES)} }};",
           "// Each entry starts a run: code point << 5 | index into categories.",
           "pub const category_runs = [_]u32{", *rows(category_runs(), 8, lambda v: f"0x{v:08X}"), "};",
           f"// First, last, canonical combining class, for characters assigned by Unicode {NORMALIZATION}.",
           "pub const combining = [_][3]u21{", *rows(combining_runs(assigned), 4, triple), "};",
           f"// Code point, first, second (0 for a singleton) as of Unicode {NORMALIZATION}; Hangul is algorithmic.",
           "pub const decompositions = [_][3]u21{", *rows(decompositions, 4, triple), "};",
           "// First, second, composite for primary composites, sorted by pair.",
           "pub const compositions = [_][3]u21{", *rows(compositions, 4, triple), "};",
           "// Non-ASCII code points whose simple case folding is an ASCII letter.",
           "pub const ascii_folds = [_][2]u21{", *rows(folds, 4, triple), "};",
           "// Adjacent ASCII pairs inside multi-character case foldings, such as ss for U+00DF.",
           "pub const ascii_multi_folds = [_][]const u8{", *rows(multi, 8, lambda p: f'"{p}"'), "};"]
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file differs")
    args = parser.parse_args()
    if unicodedata.unidata_version != VERSION:
        sys.exit(f"Python has Unicode {unicodedata.unidata_version}; the tokenizer tables need {VERSION}")
    path = ROOT / "zig/src/core/tokenizer/unicode_data.zig"
    text = render()
    if args.check:
        sys.exit(0 if path.read_text() == text else f"{path} is stale; rerun tools/zig/unicode_tables.py")
    path.write_text(text)
    print(f"Wrote {path.relative_to(ROOT)} (Unicode {VERSION}, normalization {NORMALIZATION})")


if __name__ == "__main__":
    main()
